Typesync update
AndreaPontrandolfo/sheriff pull request #312
Opened 2024-12-03 21:43 UTC by lishaduck

Closes #295, closes #297, closes #193.

2024-12-03 21:47 UTC, lishaduck commented
Works!

2025-01-01 23:23 UTC, AndreaPontrandolfo requested changes

2025-01-01 23:23 UTC, AndreaPontrandolfo commented on turbo.json
> +      "inputs": ["**/package.json", ".typesyncrc"]
uhm, either we don't specify the inputs or we add an empty `.typesyncrc` file. Otherwise the first time that we add a config file for typescync we are gonna run into trouble.

2025-01-01 23:25 UTC, lishaduck commented on turbo.json
> +      "inputs": ["**/package.json", ".typesyncrc"]
I thought I'd added a `.typesyncrc` file, but even if not, is there an issue with specifying a non-existent file?

2025-01-01 23:30 UTC, AndreaPontrandolfo requested changes
@lishaduck 

Please remove the whole tilde (~) thing. It's not needed and it makes my head spin.

2025-01-01 23:30 UTC, AndreaPontrandolfo commented on turbo.json
> +      "inputs": ["**/package.json", ".typesyncrc"]
> is there an issue with specifying a non-existent file?

Definitely yes. It creates confusion both now and for our future selfs.

2025-01-02 01:20 UTC, lishaduck commented
> Please remove the whole tilde (~) thing. It's not needed and it makes my head spin.

I can, but first, can you read the rational?
- [typsync's reasoning](https://github.com/jeffijoe/typesync#:~:text=When%20writing%20the,match%2016.14.*.)
- [definitelytyped reasoning](https://github.com/DefinitelyTyped/DefinitelyTyped?tab=readme-ov-file#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library)

Pedantically, the _most_ correct thing would be to pin types to `=`, but that's a bit over top. `~` balances it.

2025-01-02 15:24 UTC, AndreaPontrandolfo commented
> > Please remove the whole tilde (~) thing. It's not needed and it makes my head spin.
> 
> I can, but first, can you read the rational?

I did. Still don't get it.

As an example, think about Lodash. Lodash stopped being updated 9 years ago. What does it matter which version of the typings we are importing? Of course we want the latest.

Seriously i don't want to deal with any of that.

2025-01-02 16:42 UTC, lishaduck commented
> I did. Still don't get it.
> 
> As an example, think about Lodash. Lodash stopped being updated 9 years ago. What does it matter which version of the typings we are importing? Of course we want the latest.

Lodash v4 is still "in progress", but let's take react:
Say you're a package with a minimum dependency on React "^18.1", and React 18.2.0 comes out. You could upgrade the types package to 18.2.0, but then you wouldn't get any warning when you use 18.2.0 features, and could inadvertently make a breaking change. With a lockfile, you have to manually upgrade either way, so it doesn't really make a difference if you want the latest, you'll get an older version until you upgrade either way. 

> Seriously i don't want to deal with any of that.

I'll go change it, I just wanted to ensure you understood the why.

2025-01-02 18:36 UTC, AndreaPontrandolfo requested changes

2025-01-02 18:36 UTC, AndreaPontrandolfo commented on turbo.json
> +      "inputs": ["**/package.json", ".typesyncrc"]
still waiting on this

2025-01-02 18:37 UTC, AndreaPontrandolfo commented
@lishaduck on a side note, does `pnpm dev` works on your end? It's still broken on mine.

2025-01-02 19:19 UTC, lishaduck commented
> @lishaduck on a side note, does `pnpm dev` works on your end? It's still broken on mine.

I'd gotten it working, but it seems to have broken again.

2025-01-02 19:41 UTC, lishaduck commented
> > @lishaduck on a side note, does `pnpm dev` works on your end? It's still broken on mine.
> 
> I'd gotten it working, but it seems to have broken again.

Made some tweaks. It's easy enough to get to work, but it's a little finicky. Are you fine with removing `dev:norebuild`?

2025-01-02 19:49 UTC, lishaduck commented
> Are you fine with removing `dev:norebuild` (the issues are just that I didn't want to break it)?

I think I figured out how to fix it.

2025-01-03 18:26 UTC, lishaduck commented
@AndreaPontrandolfo, ping

(I'd like to get all my open PRs here and in fsecond merged today if possible as school restarts on Monday.)

2025-01-04 18:12 UTC, AndreaPontrandolfo requested changes

2025-01-04 18:12 UTC, AndreaPontrandolfo commented on turbo.json
> +      "dependsOn": ["^topo", "^build"],
can you remove this?

2025-01-05 10:31 UTC, AndreaPontrandolfo approved these changes

2025-01-05 10:32 UTC, merged